<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-EVHKK01" ignored="0" name="Test" tests="3" failures="1" timestamp="2020-08-05T16:18:55 IST" time="0.091" errors="0">
  <testcase name="failed_case" time="0.01" classname="listenersdemo.demotestcases">
    <failure type="java.lang.AssertionError" message="expected [13] but found [12]">
      <![CDATA[java.lang.AssertionError: expected [13] but found [12]
at listenersdemo.demotestcases.failed_case(demotestcases.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- failed_case -->
  <testcase name="passed_case" time="0.001" classname="listenersdemo.demotestcases"/>
  <testcase name="skipped_case" time="0.0" classname="listenersdemo.demotestcases">
    <skipped/>
  </testcase> <!-- skipped_case -->
</testsuite> <!-- Test -->
